# Generated by Django 2.2.4 on 2019-10-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0002_auto_20191030_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='longetude',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
    ]
