# Generated by Django 2.2.6 on 2019-11-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0003_auto_20191030_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichadoenca',
            old_name='saudeMenta',
            new_name='saudeMental',
        ),
    ]
