# Generated by Django 2.2.6 on 2019-11-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0004_auto_20191103_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadoenca',
            name='acamado',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='avcDerrame',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='cancer',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='cbo',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='cnes',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='cnsCidadao',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='cnsProfissional',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='cnsresponsavelFamiliar',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='dataNascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='diabetes',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='doencaCardiaca',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='doencaRespiratoria',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='domiciliado',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='fumante',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='gestante',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='hensaniase',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='hipertensaoArterial',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='ine',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='infarto',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='internacao',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='microarea',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='nomeCompleto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='nomeSocial',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='plantasMedicinais',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='praticasIntegrativasComplementares',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='problemaRins',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='racaCor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='responsavelFamiliar',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='saudeMental',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='telefoneCelular',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='tuberculose',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='usaAlcool',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='usaDrogas',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
