# Generated by Django 2.2.6 on 2019-11-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0007_auto_20191103_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadoenca',
            name='cbo',
        ),
        migrations.RemoveField(
            model_name='fichadoenca',
            name='cnes',
        ),
        migrations.RemoveField(
            model_name='fichadoenca',
            name='data',
        ),
        migrations.RemoveField(
            model_name='fichadoenca',
            name='ine',
        ),
    ]
