# Generated by Django 2.2.6 on 2019-11-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0008_auto_20191103_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='cbo',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='cnes',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='ine',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
