# Generated by Django 2.2.6 on 2019-11-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0009_auto_20191103_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='data',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
