# Generated by Django 2.2.6 on 2019-11-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0010_fichadoenca_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='cnsCidadao',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='cnsresponsavelFamiliar',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='dataNascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='microarea',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='nomeCompleto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='nomeSocial',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='responsavelFamiliar',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
