# Generated by Django 2.2.6 on 2019-11-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0011_auto_20191105_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadoenca',
            name='responsavelFamiliar',
        ),
    ]
