# Generated by Django 2.2.6 on 2019-11-07 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0014_auto_20191106_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadoenca',
            name='cnsresponsavelFamiliar',
        ),
        migrations.RemoveField(
            model_name='fichadoenca',
            name='dataNascimento',
        ),
        migrations.RemoveField(
            model_name='fichadoenca',
            name='microarea',
        ),
        migrations.RemoveField(
            model_name='fichadoenca',
            name='nomeCompleto',
        ),
        migrations.RemoveField(
            model_name='fichadoenca',
            name='nomeSocial',
        ),
    ]
