# Generated by Django 2.2.6 on 2019-11-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0016_auto_20191106_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='dataNascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='nomeCompleto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='nomeSocial',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
