# Generated by Django 2.2.6 on 2019-11-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0017_auto_20191106_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadoenca',
            name='dataNascimento',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
