# Generated by Django 2.2.6 on 2019-11-07 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0018_auto_20191106_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadoenca',
            name='dataNascimento',
        ),
        migrations.RemoveField(
            model_name='fichadoenca',
            name='nomeSocial',
        ),
    ]
