# Generated by Django 2.2.6 on 2019-11-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0019_auto_20191106_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='nomeSocial',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
