# Generated by Django 2.2.6 on 2019-11-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0020_fichadoenca_nomesocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='dataNascimento',
            field=models.DateField(null=True),
        ),
    ]
