# Generated by Django 2.2.4 on 2019-11-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0022_auto_20191106_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=120, null=True),
        ),
    ]
