# Generated by Django 2.2.6 on 2019-11-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0023_fichadoenca_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadoenca',
            name='sexo',
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='responsavelFamiliar',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=120, null=True),
        ),
    ]
