# Generated by Django 2.2.6 on 2019-11-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0025_fichadoenca_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='bairro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='cidade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='endereco',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='racaCor',
            field=models.CharField(blank=True, choices=[('Branca', 'Branca'), ('Preta', 'Preta'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='telefoneCelular',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='uf',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='responsavelFamiliar',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichadoenca',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10, null=True),
        ),
    ]
