# Generated by Django 2.2.6 on 2019-11-09 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0026_auto_20191109_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadoenca',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='fichadoenca',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='fichadoenca',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='fichadoenca',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='fichadoenca',
            name='uf',
        ),
    ]
