# Generated by Django 2.2.6 on 2019-11-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0027_auto_20191109_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='bairro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='cidade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='endereco',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='uf',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
