# Generated by Django 2.2.6 on 2019-11-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0028_auto_20191109_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='gestante',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='peso',
            field=models.CharField(blank=True, choices=[('Abaixo do peso', 'Abaixo do peso'), ('Peso adequado', 'Peso adequado'), ('Acima do peso', 'Acima do peso')], max_length=20, null=True),
        ),
    ]
