# Generated by Django 2.2.6 on 2019-11-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0029_auto_20191109_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='doencaRespiratoria',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='fumante',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
    ]
