# Generated by Django 2.2.6 on 2019-11-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0030_auto_20191109_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='acamado',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='avcDerrame',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='cancer',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='doencaCardiaca',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='domiciliado',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='hensaniase',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='hipertensaoArterial',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='infarto',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='internacao',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='plantasMedicinais',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='problemaRins',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='saudeMental',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='tuberculose',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='usaAlcool',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='usaDrogas',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
    ]
