# Generated by Django 2.2.6 on 2019-11-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0031_auto_20191109_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='longetude',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
    ]
