# Generated by Django 2.2.3 on 2019-11-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0033_auto_20191110_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadoenca',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='fichadoenca',
            name='longitude',
        ),
    ]
