# Generated by Django 2.2.3 on 2019-11-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0034_auto_20191113_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
    ]
