# Generated by Django 2.2.3 on 2019-11-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0036_auto_20191113_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadoenca',
            name='longitude',
            field=models.DecimalField(decimal_places=13, max_digits=15, null=True),
        ),
    ]
