# Generated by Django 2.2.3 on 2019-11-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaudeMap', '0038_auto_20191113_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadoenca',
            name='latitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fichadoenca',
            name='longitude',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
