# Generated by Django 2.2.4 on 2019-10-23 01:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaDoenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnsProfissional', models.CharField(max_length=15)),
                ('cbo', models.CharField(max_length=6)),
                ('cnes', models.CharField(max_length=7)),
                ('ine', models.CharField(max_length=10)),
                ('data', models.DateField()),
                ('cnsCidadao', models.CharField(max_length=15)),
                ('responsavelFamiliar', models.CharField(max_length=3)),
                ('cnsresponsavelFamiliar', models.CharField(max_length=10)),
                ('microarea', models.CharField(max_length=2)),
                ('nomeCompleto', models.CharField(max_length=255)),
                ('nomeSocial', models.CharField(max_length=255)),
                ('dataNascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('racaCor', models.CharField(max_length=10)),
                ('telefoneCelular', models.BigIntegerField()),
                ('email', models.CharField(max_length=255)),
                ('gestante', models.CharField(max_length=3)),
                ('peso', models.CharField(max_length=255)),
                ('fumante', models.CharField(max_length=3)),
                ('usaAlcool', models.CharField(max_length=3)),
                ('usaDrogas', models.CharField(max_length=3)),
                ('hipertensaoArterial', models.CharField(max_length=3)),
                ('diabetes', models.CharField(max_length=3)),
                ('avcDerrame', models.CharField(max_length=3)),
                ('infarto', models.CharField(max_length=3)),
                ('doencaCardiaca', models.CharField(max_length=3)),
                ('problemaRins', models.CharField(max_length=3)),
                ('doencaRespiratoria', models.CharField(max_length=3)),
                ('hensaniase', models.CharField(max_length=3)),
                ('tuberculose', models.CharField(max_length=3)),
                ('cancer', models.CharField(max_length=3)),
                ('internacao', models.CharField(max_length=3)),
                ('saudeMenta', models.CharField(max_length=3)),
                ('acamado', models.CharField(max_length=3)),
                ('domiciliado', models.CharField(max_length=3)),
                ('plantasMedicinais', models.CharField(max_length=3)),
                ('praticasIntegrativasComplementares', models.CharField(max_length=3)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
